# Generated by Django 3.0.1 on 2020-02-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testapp.managers


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scrap',
            managers=[
                ('objects', testapp.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='scrap_users',
            field=models.ManyToManyField(related_name='get_scrap', through='testapp.Scrap', to='testapp.Post'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
