# Generated by Django 3.0.1 on 2020-02-05 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200205_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scrap_users',
        ),
        migrations.AddField(
            model_name='post',
            name='scrap_users',
            field=models.ManyToManyField(related_name='get_scrap', through='testapp.Scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
