# Generated by Django 3.0.1 on 2020-02-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200205_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scrap',
            new_name='Scrapt',
        ),
        migrations.AlterModelManagers(
            name='scrapt',
            managers=[
            ],
        ),
    ]
