# Generated by Django 3.0.1 on 2020-02-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200205_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapt',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='joined_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='cancel_date',
        ),
        migrations.RemoveField(
            model_name='scrapt',
            name='cancel_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
