# Generated by Django 3.0.1 on 2020-02-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200212_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='is_tag',
            field=models.BooleanField(default=True),
        ),
    ]
