# Generated by Django 3.0.1 on 2020-02-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_hashtag_is_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='created',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='user',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_posttag', to='testapp.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_posttag', to='testapp.HashTag')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(related_name='get_hashtag', through='testapp.PostTag', to='testapp.HashTag'),
        ),
    ]
