# Generated by Django 3.0.1 on 2020-02-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20200216_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='public',
            new_name='is_public',
        ),
    ]
