# Generated by Django 3.0.1 on 2020-02-17 06:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20200216_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_search',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
