# Generated by Django 3.0.1 on 2020-02-17 06:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_user_recent_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_search',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
