# Generated by Django 3.0.1 on 2020-02-17 06:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20200217_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_search',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
