# Generated by Django 3.0.1 on 2020-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20200217_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reason_for_report',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
