# Generated by Django 3.0.1 on 2020-02-18 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_post_reason_for_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reason_for_report',
        ),
        migrations.RemoveField(
            model_name='post',
            name='report',
        ),
        migrations.RemoveField(
            model_name='post',
            name='report_date',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(default='', max_length=200)),
                ('post_caption', models.TextField(verbose_name='내용')),
                ('comment_contents', models.TextField(verbose_name='댓글')),
                ('reason', models.IntegerField(choices=[(0, '기타'), (1, '스팸'), (2, '욕설 및 비방'), (3, '음란물'), (4, '무단도용')], default=-1)),
                ('detail', models.CharField(default='', max_length=251)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testapp_report_comment_related', to='testapp.Comment')),
                ('post', models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testapp_report_post_related', to='testapp.Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testapp_report_user_related', to=settings.AUTH_USER_MODEL, to_field='user_uid')),
            ],
        ),
    ]
