# Generated by Django 3.0.1 on 2020-02-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20200218_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment_contents',
            field=models.TextField(default='null', verbose_name='댓글'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post_caption',
            field=models.TextField(default='null', verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post_url',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
