# Generated by Django 3.0.1 on 2020-02-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_auto_20200218_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='comment_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testapp_report_comment_owner_related', to=settings.AUTH_USER_MODEL, to_field='user_uid'),
        ),
        migrations.AddField(
            model_name='report',
            name='post_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testapp_report_post_owner_related', to=settings.AUTH_USER_MODEL, to_field='user_uid'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testapp_report_reporter_related', to=settings.AUTH_USER_MODEL, to_field='user_uid'),
        ),
    ]
