# Generated by Django 3.0.1 on 2020-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_20200218_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment_owner',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='post_owner',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
