# Generated by Django 3.0.1 on 2020-02-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_auto_20200218_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(default='', verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='detail',
            field=models.TextField(default='', verbose_name='상세내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post_caption',
            field=models.TextField(default='null', verbose_name='게시물 내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post_url',
            field=models.CharField(default='null', max_length=200, verbose_name='이미지'),
        ),
    ]
