# Generated by Django 3.0.1 on 2020-02-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_auto_20200219_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='handling',
            field=models.BooleanField(default=False),
        ),
    ]
