# Generated by Django 3.0.1 on 2020-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_report_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='handling',
            field=models.BooleanField(default=False, verbose_name='신고처리'),
        ),
    ]
