# Generated by Django 3.0.1 on 2020-02-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_auto_20200219_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='handling',
            field=models.IntegerField(choices=[(0, '처리전'), (1, '게시물 처리'), (2, '댓글 처리')], default=False, verbose_name='신고처리'),
        ),
    ]
