# Generated by Django 3.0.1 on 2020-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_auto_20200219_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='handling',
            field=models.IntegerField(choices=[(0, '신고 x'), (1, '게시물 전'), (2, '게시물 후'), (3, '댓글 전'), (4, '댓글 후')], default=0, verbose_name='신고처리'),
        ),
    ]
