# Generated by Django 3.0.1 on 2020-02-20 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_auto_20200219_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_check',
            field=models.BooleanField(default=True, verbose_name='검사'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(22001, '사진 반려'), (22002, '사진 통과'), (22003, '댓글 남김'), (22004, '규칙 위반 게시물'), (22005, '규칙 위반 댓글')], verbose_name='알림 종류')),
                ('confirmation', models.BooleanField(default=False, verbose_name='확인')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testapp_notice_post_related', to='testapp.Post')),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testapp_notice_report_related', to='testapp.Report')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testapp_notice_receiver_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
