# Generated by Django 3.0.1 on 2020-02-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_auto_20200220_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='Report',
            new_name='report',
        ),
    ]
