# Generated by Django 3.0.1 on 2020-02-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0030_auto_20200220_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testapp_notice_post_related', to='testapp.Post'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testapp_notice_report_related', to='testapp.Report'),
        ),
    ]
