# Generated by Django 3.0.1 on 2020-02-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_auto_20200220_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_check',
        ),
    ]
