# Generated by Django 3.0.1 on 2020-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0033_remove_post_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_check',
            field=models.IntegerField(choices=[(22000, '검사 전'), (22001, '사진 통과'), (22002, '잘못된 위치정보'), (22004, '부적절한 사진')], default=22001, verbose_name='검사'),
        ),
    ]
