# Generated by Django 3.0.1 on 2020-02-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0036_auto_20200220_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='handling',
        ),
    ]
