# Generated by Django 3.0.1 on 2020-02-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0040_notice_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='reason_detail',
        ),
        migrations.RemoveField(
            model_name='report',
            name='comment_owner',
        ),
        migrations.RemoveField(
            model_name='report',
            name='post_owner',
        ),
        migrations.AddField(
            model_name='report',
            name='reason_detail',
            field=models.TextField(default='', verbose_name='사유 작성란'),
        ),
    ]
